/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import classes.DB;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Sheha
 */
public class add extends javax.swing.JPanel {

    /**
     * Creates new form add
     */
    public add() {
        initComponents();
        b_date.setText(new SimpleDateFormat("yyy-MM-dd").format(new Date()));
      
        loadSupp();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        b_acidity = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        b_date = new javax.swing.JTextField();
        b_qty = new javax.swing.JTextField();
        b_fat = new javax.swing.JTextField();
        b_ts = new javax.swing.JTextField();
        b_ph = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        a_acidity = new javax.swing.JTextField();
        a_buyer_200 = new javax.swing.JTextField();
        a_sample = new javax.swing.JTextField();
        a_ts = new javax.swing.JTextField();
        a_ph = new javax.swing.JTextField();
        a_qty_2 = new javax.swing.JTextField();
        a_qty_1 = new javax.swing.JTextField();
        a_buyer_20 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setText("Acidity");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setText("Production Date");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 21, -1, 40));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setText("Supplier Name");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setText("Quantity");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setText("%");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 200, 20, 30));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setText("Total Solids(Ts)");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setText("pH");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, -1));

        b_acidity.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        b_acidity.setText("0");
        b_acidity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                b_acidityFocusGained(evt);
            }
        });
        b_acidity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_acidityActionPerformed(evt);
            }
        });
        b_acidity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                b_acidityKeyTyped(evt);
            }
        });
        jPanel5.add(b_acidity, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 230, 30));

        jComboBox1.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select name" }));
        jPanel5.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 82, 230, 30));

        b_date.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jPanel5.add(b_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 230, 30));

        b_qty.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        b_qty.setText("0");
        b_qty.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                b_qtyFocusGained(evt);
            }
        });
        b_qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_qtyActionPerformed(evt);
            }
        });
        b_qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                b_qtyKeyTyped(evt);
            }
        });
        jPanel5.add(b_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 230, 30));

        b_fat.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        b_fat.setText("0");
        b_fat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                b_fatFocusGained(evt);
            }
        });
        b_fat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_fatActionPerformed(evt);
            }
        });
        b_fat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                b_fatKeyTyped(evt);
            }
        });
        jPanel5.add(b_fat, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 210, 30));

        b_ts.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        b_ts.setText("0");
        b_ts.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                b_tsFocusGained(evt);
            }
        });
        b_ts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_tsActionPerformed(evt);
            }
        });
        b_ts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                b_tsKeyTyped(evt);
            }
        });
        jPanel5.add(b_ts, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 230, 30));

        b_ph.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        b_ph.setText("0");
        b_ph.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                b_phFocusGained(evt);
            }
        });
        b_ph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_phActionPerformed(evt);
            }
        });
        b_ph.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                b_phKeyTyped(evt);
            }
        });
        jPanel5.add(b_ph, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 230, 30));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel15.setText("Fat ");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        jPanel7.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 760, 430));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Before Production", jPanel2);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel8.setText("Acidity");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel10.setText("Buyer Name");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel11.setText("Quantity ");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel12.setText("Samples");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel13.setText("Total Solids(Ts)");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel14.setText("pH");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        a_acidity.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        a_acidity.setText("0");
        a_acidity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                a_acidityFocusGained(evt);
            }
        });
        a_acidity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a_acidityKeyTyped(evt);
            }
        });
        jPanel6.add(a_acidity, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 230, 30));

        a_buyer_200.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        a_buyer_200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_buyer_200ActionPerformed(evt);
            }
        });
        jPanel6.add(a_buyer_200, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 110, 30));

        a_sample.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        a_sample.setText("0");
        a_sample.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                a_sampleFocusGained(evt);
            }
        });
        a_sample.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_sampleActionPerformed(evt);
            }
        });
        a_sample.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a_sampleKeyTyped(evt);
            }
        });
        jPanel6.add(a_sample, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 230, 30));

        a_ts.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        a_ts.setText("0");
        a_ts.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                a_tsFocusGained(evt);
            }
        });
        a_ts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_tsActionPerformed(evt);
            }
        });
        a_ts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a_tsKeyTyped(evt);
            }
        });
        jPanel6.add(a_ts, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 230, 30));

        a_ph.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        a_ph.setText("0");
        a_ph.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                a_phFocusGained(evt);
            }
        });
        a_ph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_phActionPerformed(evt);
            }
        });
        a_ph.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a_phKeyTyped(evt);
            }
        });
        jPanel6.add(a_ph, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 230, 30));

        a_qty_2.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        a_qty_2.setText("0");
        a_qty_2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                a_qty_2FocusGained(evt);
            }
        });
        a_qty_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_qty_2ActionPerformed(evt);
            }
        });
        a_qty_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a_qty_2KeyTyped(evt);
            }
        });
        jPanel6.add(a_qty_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 110, 30));

        a_qty_1.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        a_qty_1.setText("0");
        a_qty_1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                a_qty_1FocusGained(evt);
            }
        });
        a_qty_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_qty_1ActionPerformed(evt);
            }
        });
        a_qty_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a_qty_1KeyTyped(evt);
            }
        });
        jPanel6.add(a_qty_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 110, 30));

        a_buyer_20.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        a_buyer_20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_buyer_20ActionPerformed(evt);
            }
        });
        jPanel6.add(a_buyer_20, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 110, 30));

        jLabel16.setText("200L");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, -1, -1));

        jLabel17.setText("20L");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, -1));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 760, 430));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("After Production", jPanel3);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 970, 550));

        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jButton2.setText("SAVE ALL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 590, 120, 40));

        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jButton1.setText("CLEAR ALL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 590, 120, 40));

        jPanel8.setBackground(new java.awt.Color(84, 66, 23));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(195, 217, 79));
        jLabel9.setText("ADD RECORD");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, -1, 30));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            
            if (JOptionPane.showConfirmDialog(this, "Are you sure want to add record?") == 0) {
                
                ResultSet rs = DB.search("select id_sup from supplier where name='" + jComboBox1.getSelectedItem().toString() + "'");
                //before
                if (rs.next()) {
                    
                    DB.iud("insert into before_production (date,qty,fat,ts,ph,acidity,supplier_id_sup,buyer_1,buyer_2,qty_1,qty_2,sample,ts_2,ph_2,acidity_2) values ('" + b_date.getText() + "','" + Integer.parseInt(b_qty.getText()) + "','" + Double.parseDouble(b_fat.getText()) + "','" + Double.parseDouble(b_ts.getText()) + "','" + Double.parseDouble(b_ph.getText()) + "','" + Double.parseDouble(b_acidity.getText()) + "','" + rs.getString("id_sup") + "','" + a_buyer_20.getText() + "','"+a_buyer_200.getText()+"','" + a_qty_1.getText() + "','" + a_qty_2.getText() + "','" + Integer.parseInt(a_sample.getText()) + "','" + Double.parseDouble(a_ts.getText()) + "','" + Double.parseDouble(a_ph.getText()) + "','" + Double.parseDouble(a_acidity.getText()) + "')");
                    
                }
                
                JOptionPane.showMessageDialog(this, "Successfully added!");
                clear();
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void a_tsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_tsActionPerformed
     a_ph.grabFocus();
    }//GEN-LAST:event_a_tsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        clear();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void b_qtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b_qtyKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            
            evt.consume();
        }
        if (b_qty.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_b_qtyKeyTyped

    private void b_fatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b_fatKeyTyped
       
        if (b_fat.getText().length() >= 8) {
            evt.consume();
        }
    }//GEN-LAST:event_b_fatKeyTyped

    private void b_tsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b_tsKeyTyped
       
        if (b_ts.getText().length() >= 8) {
            evt.consume();
        }
    }//GEN-LAST:event_b_tsKeyTyped

    private void b_phKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b_phKeyTyped
       
        if (b_ph.getText().length() >= 8) {
            evt.consume();
        }
    }//GEN-LAST:event_b_phKeyTyped

    private void b_acidityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b_acidityKeyTyped
      
        if (b_acidity.getText().length() >= 8) {
            evt.consume();
        }
    }//GEN-LAST:event_b_acidityKeyTyped

    private void a_qty_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a_qty_1KeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            
            evt.consume();
        }
        if (a_qty_1.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_a_qty_1KeyTyped

    private void a_qty_2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a_qty_2KeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            
            evt.consume();
        }
        if (a_qty_2.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_a_qty_2KeyTyped

    private void a_sampleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a_sampleKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            
            evt.consume();
        }
        if (a_sample.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_a_sampleKeyTyped

    private void a_tsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a_tsKeyTyped
       
        if (a_ts.getText().length() >= 8) {
            evt.consume();
        }
    }//GEN-LAST:event_a_tsKeyTyped

    private void a_phKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a_phKeyTyped
      
        if (a_ph.getText().length() >= 8) {
            evt.consume();
        }
    }//GEN-LAST:event_a_phKeyTyped

    private void a_acidityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a_acidityKeyTyped
        
        if (a_acidity.getText().length() >= 8) {
            evt.consume();
        }
    }//GEN-LAST:event_a_acidityKeyTyped

    private void b_qtyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_b_qtyFocusGained
      b_qty.setText("");
    }//GEN-LAST:event_b_qtyFocusGained

    private void b_qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_qtyActionPerformed
       b_fat.grabFocus();
    }//GEN-LAST:event_b_qtyActionPerformed

    private void b_fatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_b_fatFocusGained
       
        b_fat.setText("");
    }//GEN-LAST:event_b_fatFocusGained

    private void b_fatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_fatActionPerformed
      
        b_ts.grabFocus();
    }//GEN-LAST:event_b_fatActionPerformed

    private void b_tsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_b_tsFocusGained
      b_ts.setText("");
    }//GEN-LAST:event_b_tsFocusGained

    private void b_tsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_tsActionPerformed
       b_ph.grabFocus();
    }//GEN-LAST:event_b_tsActionPerformed

    private void b_phFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_b_phFocusGained
     b_ph.setText("");
    }//GEN-LAST:event_b_phFocusGained

    private void b_phActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_phActionPerformed
     b_acidity.grabFocus();
    }//GEN-LAST:event_b_phActionPerformed

    private void b_acidityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_b_acidityFocusGained
    b_acidity.setText("");
    }//GEN-LAST:event_b_acidityFocusGained

    private void b_acidityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_acidityActionPerformed
      a_buyer_20.grabFocus();
    }//GEN-LAST:event_b_acidityActionPerformed

    private void a_buyer_20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_buyer_20ActionPerformed
    a_buyer_200.grabFocus();
    }//GEN-LAST:event_a_buyer_20ActionPerformed

    private void a_buyer_200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_buyer_200ActionPerformed
      a_qty_1.grabFocus();
    }//GEN-LAST:event_a_buyer_200ActionPerformed

    private void a_qty_1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_a_qty_1FocusGained
      a_qty_1.setText("");
    }//GEN-LAST:event_a_qty_1FocusGained

    private void a_qty_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_qty_1ActionPerformed
     
        a_qty_2.grabFocus();
    }//GEN-LAST:event_a_qty_1ActionPerformed

    private void a_qty_2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_a_qty_2FocusGained
        a_qty_2.setText("");
    }//GEN-LAST:event_a_qty_2FocusGained

    private void a_qty_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_qty_2ActionPerformed
      a_sample.grabFocus();
    }//GEN-LAST:event_a_qty_2ActionPerformed

    private void a_sampleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_a_sampleFocusGained
 a_sample.setText("");
    }//GEN-LAST:event_a_sampleFocusGained

    private void a_sampleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_sampleActionPerformed
     a_ts.grabFocus();
    }//GEN-LAST:event_a_sampleActionPerformed

    private void a_tsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_a_tsFocusGained
       a_ts.setText("");
    }//GEN-LAST:event_a_tsFocusGained

    private void a_phFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_a_phFocusGained
     a_ph.setText("");
    }//GEN-LAST:event_a_phFocusGained

    private void a_phActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_phActionPerformed
    a_acidity.grabFocus();
    }//GEN-LAST:event_a_phActionPerformed

    private void a_acidityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_a_acidityFocusGained
      a_acidity.setText("");
    }//GEN-LAST:event_a_acidityFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a_acidity;
    private javax.swing.JTextField a_buyer_20;
    private javax.swing.JTextField a_buyer_200;
    private javax.swing.JTextField a_ph;
    private javax.swing.JTextField a_qty_1;
    private javax.swing.JTextField a_qty_2;
    private javax.swing.JTextField a_sample;
    private javax.swing.JTextField a_ts;
    private javax.swing.JTextField b_acidity;
    private javax.swing.JTextField b_date;
    private javax.swing.JTextField b_fat;
    private javax.swing.JTextField b_ph;
    private javax.swing.JTextField b_qty;
    private javax.swing.JTextField b_ts;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    private void loadSupp() {
        
        try {
            
            ResultSet rs = DB.search("select name from supplier");
            Vector v = new Vector();
            
            while (rs.next()) {
                
                v.add(rs.getString("name"));
            }
            jComboBox1.setModel(new DefaultComboBoxModel(v));
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }
    
    private void clear() {
        try {
            
            jComboBox1.setSelectedIndex(0);
            b_acidity.setText("0");
            b_fat.setText("0");
            b_ph.setText("0");
            b_qty.setText("0");
            b_ts.setText("0");
            
            a_buyer_200.setText("");
            a_acidity.setText("0");
            a_ph.setText("0");
            a_qty_1.setText("0");
            a_qty_2.setText("0");
            a_sample.setText("0");
            a_ts.setText("0");
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }
    
}
