/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import classes.DB;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Sheha
 */
public class find extends javax.swing.JPanel {

    /**
     * Creates new form find
     */
    public find() {
        initComponents();
        loadTBL("select * from before_production order by date");
        loadSupp();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        a_acidity = new javax.swing.JTextField();
        a_sample = new javax.swing.JTextField();
        a_ts = new javax.swing.JTextField();
        a_ph = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        record_id = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        b_acidity = new javax.swing.JTextField();
        b_ph = new javax.swing.JTextField();
        b_ts = new javax.swing.JTextField();
        b_fat = new javax.swing.JTextField();
        b_qty = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        a_buyer_20 = new javax.swing.JTextField();
        a_buyer_200 = new javax.swing.JTextField();
        a_qty_1 = new javax.swing.JTextField();
        a_qty_2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Date", "Supplier", "Qty", "Fat", "Ts", "pH", "Acidity", "Ts", "pH", "Acidity", "Buyer20L", "Qty20L", "Buyer200L", "Qty200L", "Samples"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setMinWidth(100);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(2).setMinWidth(100);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(15).setMinWidth(80);
            jTable1.getColumnModel().getColumn(15).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(15).setMaxWidth(80);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 31, 950, 480));

        jPanel5.setBackground(new java.awt.Color(84, 66, 23));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("AFTER PRODUCTION");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, 30));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 470, 30));

        jPanel7.setBackground(new java.awt.Color(84, 66, 23));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("BEFORE PRODUCTION");
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, 30));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 530, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 960, 510));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 240, 30));

        jButton1.setText("SEARCH ALL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        jButton2.setText("SEARCH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        jButton5.setText("PRINT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 740, 50));

        jTabbedPane1.addTab("View", jPanel1);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel8.setText("Acidity");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, -1, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel12.setText("Samples");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, -1, -1));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel13.setText("Total Solids(Ts)");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, -1, -1));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel14.setText("pH");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, -1, -1));

        a_acidity.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        a_acidity.setText("0");
        a_acidity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a_acidityKeyTyped(evt);
            }
        });
        jPanel6.add(a_acidity, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 420, 230, 30));

        a_sample.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        a_sample.setText("0");
        a_sample.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a_sampleKeyTyped(evt);
            }
        });
        jPanel6.add(a_sample, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, 230, 30));

        a_ts.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        a_ts.setText("0");
        a_ts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_tsActionPerformed(evt);
            }
        });
        a_ts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a_tsKeyTyped(evt);
            }
        });
        jPanel6.add(a_ts, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, 230, 30));

        a_ph.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        a_ph.setText("0");
        a_ph.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a_phKeyTyped(evt);
            }
        });
        jPanel6.add(a_ph, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 230, 30));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setText("%");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 20, 30));

        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, 110, 50));

        jButton4.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jButton4.setText("UPDATE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 500, 120, 50));

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setText("Record ID");
        jPanel9.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 40));

        record_id.setEditable(false);
        record_id.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jPanel9.add(record_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 130, 30));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel16.setText("Production Date");
        jPanel9.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, 40));

        date.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jPanel9.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 230, 30));

        jPanel6.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 680, 80));

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setText("Supplier Name");
        jPanel10.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setText("Quantity");
        jPanel10.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel15.setText("Fat ");
        jPanel10.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setText("Total Solids(Ts)");
        jPanel10.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setText("pH");
        jPanel10.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setText("Acidity");
        jPanel10.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        b_acidity.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        b_acidity.setText("0");
        b_acidity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                b_acidityKeyTyped(evt);
            }
        });
        jPanel10.add(b_acidity, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 230, 30));

        b_ph.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        b_ph.setText("0");
        b_ph.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                b_phKeyTyped(evt);
            }
        });
        jPanel10.add(b_ph, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 230, 30));

        b_ts.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        b_ts.setText("0");
        b_ts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                b_tsKeyTyped(evt);
            }
        });
        jPanel10.add(b_ts, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 230, 30));

        b_fat.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        b_fat.setText("0");
        b_fat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                b_fatKeyTyped(evt);
            }
        });
        jPanel10.add(b_fat, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 210, 30));

        b_qty.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        b_qty.setText("0");
        b_qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                b_qtyKeyTyped(evt);
            }
        });
        jPanel10.add(b_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 230, 30));

        jComboBox1.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select name" }));
        jPanel10.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 230, 30));

        a_buyer_20.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        a_buyer_20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_buyer_20ActionPerformed(evt);
            }
        });
        jPanel10.add(a_buyer_20, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, 110, 30));

        a_buyer_200.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        a_buyer_200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_buyer_200ActionPerformed(evt);
            }
        });
        jPanel10.add(a_buyer_200, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, 110, 30));

        a_qty_1.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        a_qty_1.setText("0");
        a_qty_1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                a_qty_1FocusGained(evt);
            }
        });
        a_qty_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_qty_1ActionPerformed(evt);
            }
        });
        a_qty_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a_qty_1KeyTyped(evt);
            }
        });
        jPanel10.add(a_qty_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, 110, 30));

        a_qty_2.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        a_qty_2.setText("0");
        a_qty_2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                a_qty_2FocusGained(evt);
            }
        });
        a_qty_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_qty_2ActionPerformed(evt);
            }
        });
        a_qty_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a_qty_2KeyTyped(evt);
            }
        });
        jPanel10.add(a_qty_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 80, 110, 30));

        jLabel19.setText("20L");
        jPanel10.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, -1, -1));

        jLabel20.setText("200L");
        jPanel10.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, -1, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel11.setText("Quantity ");
        jPanel10.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, -1, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel10.setText("Buyer Name");
        jPanel10.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, -1, 30));

        jPanel6.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 940, 480));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 965, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Update", jPanel4);

        add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 970, 620));

        jPanel8.setBackground(new java.awt.Color(84, 66, 23));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(195, 217, 79));
        jLabel9.setText("FIND RECORD");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, -1, 30));

        add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void a_acidityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a_acidityKeyTyped

        if (a_acidity.getText().length() >= 8) {
            evt.consume();
        }
    }//GEN-LAST:event_a_acidityKeyTyped

    private void a_sampleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a_sampleKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {

            evt.consume();
        }
        if (a_sample.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_a_sampleKeyTyped

    private void a_tsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_tsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a_tsActionPerformed

    private void a_tsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a_tsKeyTyped

        if (a_ts.getText().length() >= 8) {
            evt.consume();
        }
    }//GEN-LAST:event_a_tsKeyTyped

    private void a_phKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a_phKeyTyped

        if (a_ph.getText().length() >= 8) {
            evt.consume();
        }
    }//GEN-LAST:event_a_phKeyTyped

    private void b_acidityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b_acidityKeyTyped

        if (b_acidity.getText().length() >= 8) {
            evt.consume();
        }
    }//GEN-LAST:event_b_acidityKeyTyped

    private void b_phKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b_phKeyTyped

        if (b_ph.getText().length() >= 8) {
            evt.consume();
        }
    }//GEN-LAST:event_b_phKeyTyped

    private void b_tsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b_tsKeyTyped

        if (b_ts.getText().length() >= 8) {
            evt.consume();
        }
    }//GEN-LAST:event_b_tsKeyTyped

    private void b_fatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b_fatKeyTyped

        if (b_fat.getText().length() >= 8) {
            evt.consume();
        }
    }//GEN-LAST:event_b_fatKeyTyped

    private void b_qtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b_qtyKeyTyped

        if (!Character.isDigit(evt.getKeyChar())) {

            evt.consume();
        }
        if (b_qty.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_b_qtyKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            String date = new SimpleDateFormat("yyy-MM-dd").format(jDateChooser2.getDate());
            loadTBL("select * from before_production where date='" + date + "'");

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           loadTBL("select * from before_production order by date");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {

            for (int i = 0; i < jTable1.getRowCount(); i++) {

                String id = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();

                ResultSet rs = DB.search("select * from before_production where id_before_p='" + id + "'");
                if (rs.next()) {

                    record_id.setText(rs.getString("id_before_p"));
                    date.setText(rs.getString("date"));
                    ResultSet rs2 = DB.search("select name from supplier where id_sup = '" + rs.getString("supplier_id_sup") + "'");
                    if (rs2.next()) {

                        jComboBox1.setSelectedItem(rs2.getString("name"));

                    }
                    b_qty.setText(rs.getString("qty"));
                    b_fat.setText(rs.getString("fat"));
                    b_ts.setText(rs.getString("ts"));
                    b_ph.setText(rs.getString("ph"));
                    b_acidity.setText(rs.getString("acidity"));

                    a_buyer_20.setText(rs.getString("buyer_1"));
                    a_buyer_200.setText(rs.getString("buyer_2"));
                    a_qty_1.setText(rs.getString("qty_1"));
                    a_qty_2.setText(rs.getString("qty_2"));
                    a_sample.setText(rs.getString("sample"));
                    a_ts.setText(rs.getString("ts_2"));
                    a_ph.setText(rs.getString("ph_2"));
                    a_acidity.setText(rs.getString("acidity_2"));

                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            if (JOptionPane.showConfirmDialog(this, "Are you sure want to update?") == 0) {

                ResultSet rs = DB.search("select id_sup from supplier where name='" + jComboBox1.getSelectedItem().toString() + "'");
                if (rs.next()) {

                    DB.iud("update before_production set date='" + date.getText() + "' , qty='" + Integer.parseInt(b_qty.getText()) + "' , fat='" + Double.parseDouble(b_fat.getText()) + "' , ts='" + Double.parseDouble(b_ts.getText()) + "' , ph='" + Double.parseDouble(b_ph.getText()) + "' , acidity='" + Double.parseDouble(b_acidity.getText()) + "' , supplier_id_sup='" + rs.getString("id_sup") + "' , buyer_1='" + a_buyer_20.getText() + "' , buyer_2='"+a_buyer_200.getText()+"',qty_1='" + Integer.parseInt(a_qty_1.getText()) + "' , qty_2='" + Integer.parseInt(a_qty_2.getText()) + "' , sample='" + Integer.parseInt(a_sample.getText()) + "' , ts_2='" + Double.parseDouble(a_ts.getText()) + "' , ph_2='" + Double.parseDouble(a_ph.getText()) + "' , acidity_2='" + Double.parseDouble(a_acidity.getText()) + "' where id_before_p='" + record_id.getText() + "'");
                    JOptionPane.showMessageDialog(this, "Successfully updated!");
                    loadTBL("select * from before_production order by date");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
               if (JOptionPane.showConfirmDialog(this, "Are you sure want to remove?") == 0) {
               
                   DB.iud("delete from before_production where id_before_p='"+record_id.getText()+"'");
                    JOptionPane.showMessageDialog(this, "Successfully deleted!");
                    loadTBL("select * from before_production order by date");
               
               
               }
        } catch (Exception e) {
        e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void a_buyer_20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_buyer_20ActionPerformed
        a_buyer_200.grabFocus();
    }//GEN-LAST:event_a_buyer_20ActionPerformed

    private void a_buyer_200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_buyer_200ActionPerformed
        a_qty_1.grabFocus();
    }//GEN-LAST:event_a_buyer_200ActionPerformed

    private void a_qty_1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_a_qty_1FocusGained
        a_qty_1.setText("");
    }//GEN-LAST:event_a_qty_1FocusGained

    private void a_qty_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_qty_1ActionPerformed

        a_qty_2.grabFocus();
    }//GEN-LAST:event_a_qty_1ActionPerformed

    private void a_qty_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a_qty_1KeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {

            evt.consume();
        }
        if (a_qty_1.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_a_qty_1KeyTyped

    private void a_qty_2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_a_qty_2FocusGained
        a_qty_2.setText("");
    }//GEN-LAST:event_a_qty_2FocusGained

    private void a_qty_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_qty_2ActionPerformed
        a_sample.grabFocus();
    }//GEN-LAST:event_a_qty_2ActionPerformed

    private void a_qty_2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a_qty_2KeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {

            evt.consume();
        }
        if (a_qty_2.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_a_qty_2KeyTyped

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     
           int x = JOptionPane.showConfirmDialog(this, "Do you want to print ?");
        if (x == 0) {
            try {
                String path = "C:/KAP/kap_tbl.jrxml";
                
                JRTableModelDataSource jt = new JRTableModelDataSource(jTable1.getModel());
                JasperReport compileReport = JasperCompileManager.compileReport(path);

                Map<String, Object> m = new HashMap<>();
             

                JasperPrint fillReport = JasperFillManager.fillReport(compileReport, m, jt);
                JasperViewer.viewReport(fillReport, false);

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        
        
        
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a_acidity;
    private javax.swing.JTextField a_buyer_20;
    private javax.swing.JTextField a_buyer_200;
    private javax.swing.JTextField a_ph;
    private javax.swing.JTextField a_qty_1;
    private javax.swing.JTextField a_qty_2;
    private javax.swing.JTextField a_sample;
    private javax.swing.JTextField a_ts;
    private javax.swing.JTextField b_acidity;
    private javax.swing.JTextField b_fat;
    private javax.swing.JTextField b_ph;
    private javax.swing.JTextField b_qty;
    private javax.swing.JTextField b_ts;
    private javax.swing.JTextField date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField record_id;
    // End of variables declaration//GEN-END:variables

    private void loadTBL(String q1) {
        try {

            ResultSet rs = DB.search(q1);

            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
            while (rs.next()) {

                Vector v = new Vector();
                v.add(rs.getString("id_before_p"));
                v.add(rs.getString("date"));

                ResultSet rs3 = DB.search("select name from supplier where id_sup='" + rs.getString("supplier_id_sup") + "'");
                if (rs3.next()) {
                    v.add(rs3.getString("name"));
                }
                String qty = rs.getString("qty");
                String fat = rs.getString("fat");
                String ts = rs.getString("ts");
                String ph = rs.getString("ph");
                String acidity = rs.getString("acidity");

                if (qty.equals("0")) {
                    v.add("");
                } else {
                    v.add(qty);

                }
                if (fat.equals("0")) {
                    v.add("");
                } else {
                    v.add(fat);
                }
                if (ts.equals("0")) {
                    v.add("");
                } else {
                    v.add(ts);
                }
                if (ph.equals("0")) {
                    v.add("");
                } else {
                    v.add(ph);
                }
                if (acidity.equals("0")) {
                    v.add("");
                } else {
                    v.add(acidity);
                }

                String ts_2 = rs.getString("ts_2");
                String ph_2 = rs.getString("ph_2");
                String acidity_2 = rs.getString("acidity_2");

                if (ts_2.equals("0")) {
                    v.add("");

                } else {
                    v.add(ts_2);

                }
                if (ph_2.equals("0")) {
                    v.add("");

                } else {
                    v.add(ph_2);

                }
                if (acidity_2.equals("0")) {
                    v.add("");

                } else {

                    v.add(acidity_2);

                }

                v.add(rs.getString("buyer_1"));
                String qty_1_2 = rs.getString("qty_1");
                String qty_2_2 = rs.getString("qty_2");
                String sample = rs.getString("sample");
                if (qty_1_2.equals("0")) {
                    v.add("");
                } else {
                    v.add(qty_1_2);

                }
                v.add(rs.getString("buyer_2"));
                if (qty_2_2.equals("0")) {

                    v.add("");
                } else {

                    v.add(qty_2_2);
                }
                if (sample.equals("0")) {

                    v.add("");
                } else {
                    v.add(sample);

                }

                dtm.addRow(v);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadSupp() {

        try {

            ResultSet rs = DB.search("select name from supplier");
            Vector v = new Vector();

            while (rs.next()) {

                v.add(rs.getString("name"));
            }
            jComboBox1.setModel(new DefaultComboBoxModel(v));

        } catch (Exception e) {
            e.printStackTrace();
        }

    }
}
