/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import classes.DB;
import classes.EXTCLASS;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sheha
 */
public class settings extends javax.swing.JPanel {

    /**
     * Creates new form settings
     */
    public settings() {
        initComponents();
        jButton5.setEnabled(false);
        jButton6.setEnabled(false);
        jButton7.setEnabled(false);
        loadTB1();
        addUserAccess();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        un = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        pw = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        user_tb = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        user_id = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        sup_name = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        sup_contact = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        sup_tb = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        sup_id = new javax.swing.JTextField();

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(84, 66, 23));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(195, 217, 79));
        jLabel15.setText("SETTINGS");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, -1, 30));

        jPanel6.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 30));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(84, 66, 23));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADD NEW USER");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 30));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel9.setText("Username");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, 40));

        un.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jPanel2.add(un, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 180, 30));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel10.setText("Password");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, 40));

        pw.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jPanel2.add(pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 180, 30));

        user_tb.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        user_tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Username", "Password"
            }
        ));
        user_tb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user_tbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(user_tb);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 440, 310));

        jButton5.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jButton5.setText("ADD");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 90, 40));

        jButton6.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jButton6.setText("REMOVE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 100, 40));

        jButton7.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jButton7.setText("UPDATE");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 90, 40));

        user_id.setEditable(false);
        user_id.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jPanel2.add(user_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 180, 30));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel14.setText("User ID");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 460, 610));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(84, 66, 23));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ADD SUPPLIER");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, 30));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 30));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel11.setText("Full Name");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, 40));

        sup_name.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jPanel4.add(sup_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 180, 30));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel12.setText("Contact NO");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, 40));

        sup_contact.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        sup_contact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sup_contactKeyTyped(evt);
            }
        });
        jPanel4.add(sup_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 180, 30));

        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 90, 40));

        sup_tb.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        sup_tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Name", "Contact"
            }
        ));
        sup_tb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sup_tbMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(sup_tb);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 440, 310));

        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jButton3.setText("ADD");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 90, 40));

        jButton4.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jButton4.setText("REMOVE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 100, 40));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel13.setText("Supplier ID");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, 40));

        sup_id.setEditable(false);
        sup_id.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jPanel4.add(sup_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 180, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 470, 610));

        jPanel6.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 960, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {

            if (JOptionPane.showConfirmDialog(this, "Are you sure?") == 0) {

                DB.iud("insert into supplier (name,mobile) values('" + sup_name.getText() + "','" + sup_contact.getText() + "')");
                JOptionPane.showMessageDialog(this, "Successfully Added!");
                sup_name.setText(null);
                sup_contact.setText(null);
                loadTB1();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void sup_contactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sup_contactKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {

            evt.consume();
        }
        if (sup_contact.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_sup_contactKeyTyped

    private void sup_tbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sup_tbMouseClicked
        try {

            String name = "";
            String id = "";
            String contact = "";
            for (int i = 0; i < sup_tb.getRowCount(); i++) {

                id = sup_tb.getValueAt(sup_tb.getSelectedRow(), 0).toString();
                name = sup_tb.getValueAt(sup_tb.getSelectedRow(), 1).toString();
                contact = sup_tb.getValueAt(sup_tb.getSelectedRow(), 2).toString();

            }
            sup_name.setText(name);
            sup_contact.setText(contact);
            sup_id.setText(id);

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_sup_tbMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            if (JOptionPane.showConfirmDialog(this, "Are you sure want to remove?") == 0) {

                DB.iud("delete from supplier where id_sup='" + sup_id.getText() + "' ");
                JOptionPane.showMessageDialog(this, "Successfully deleted!");
                sup_id.setText(null);
                sup_name.setText(null);
                sup_contact.setText(null);

                loadTB1();

            }

        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            if (JOptionPane.showConfirmDialog(this, "Are you sure want to update?") == 0) {

                DB.iud("update supplier set name='" + sup_name.getText() + "', mobile='" + sup_contact.getText() + "' where id_sup='" + sup_id.getText() + "' ");
                JOptionPane.showMessageDialog(this, "Successfully updated!");
                sup_id.setText(null);
                sup_name.setText(null);
                sup_contact.setText(null);

                loadTB1();

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {

            if (JOptionPane.showConfirmDialog(this, "Are you sure?") == 0) {

                DB.iud("insert into login (un,pw) values('" + un.getText() + "','" + pw.getText() + "')");
                JOptionPane.showMessageDialog(this, "Successfully Added!");
                un.setText(null);
                pw.setText(null);
                loadTB2();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      
           try {
            if (JOptionPane.showConfirmDialog(this, "Are you sure want to remove?") == 0) {

                DB.iud("delete from login where idlogin='" + user_id.getText() + "' ");
                JOptionPane.showMessageDialog(this, "Successfully deleted!");
                user_id.setText(null);
                un.setText(null);
                pw.setText(null);

                loadTB2();

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void user_tbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_tbMouseClicked
         try {

            String unn = "";
            String id = "";
            String pww = "";
            for (int i = 0; i < user_tb.getRowCount(); i++) {

                id = user_tb.getValueAt(user_tb.getSelectedRow(), 0).toString();
                unn = user_tb.getValueAt(user_tb.getSelectedRow(), 1).toString();
                pww = user_tb.getValueAt(user_tb.getSelectedRow(), 2).toString();

            }
            un.setText(unn);
            pw.setText(pww);
            user_id.setText(id);

        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
        
    }//GEN-LAST:event_user_tbMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    try {
            if (JOptionPane.showConfirmDialog(this, "Are you sure want to update?") == 0) {

                DB.iud("update login set un='" + un.getText() + "', pw='" + pw.getText() + "' where idlogin='" + user_id.getText() + "' ");
                JOptionPane.showMessageDialog(this, "Successfully updated!");
                user_id.setText(null);
                un.setText(null);
                pw.setText(null);

                loadTB2();

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_jButton7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField pw;
    private javax.swing.JTextField sup_contact;
    private javax.swing.JTextField sup_id;
    private javax.swing.JTextField sup_name;
    private javax.swing.JTable sup_tb;
    private javax.swing.JTextField un;
    private javax.swing.JTextField user_id;
    private javax.swing.JTable user_tb;
    // End of variables declaration//GEN-END:variables

    private void loadTB1() {

        try {

            ResultSet rs = DB.search("select * from supplier");
            DefaultTableModel dtm = (DefaultTableModel) sup_tb.getModel();
            dtm.setRowCount(0);

            while (rs.next()) {

                Vector v = new Vector();
                v.add(rs.getString("id_sup"));
                v.add(rs.getString("name"));
                v.add(rs.getString("mobile"));
                dtm.addRow(v);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void loadTB2() {
        try {

            ResultSet rs = DB.search("select * from login");
            DefaultTableModel dtm = (DefaultTableModel) user_tb.getModel();
            dtm.setRowCount(0);

            while (rs.next()) {

                Vector v = new Vector();
                v.add(rs.getString("idlogin"));
                v.add(rs.getString("un"));
                v.add(rs.getString("pw"));
                dtm.addRow(v);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void addUserAccess() {
        try {

            if (EXTCLASS.isAdmin) {
                jButton5.setEnabled(true);
                jButton6.setEnabled(true);
                jButton7.setEnabled(true);
                loadTB2();

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }
}
